name: depthfenc
description: "DepthFence — Geospatial Land Intelligence Platform"
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  supabase_flutter: ^2.17.2
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  shared_preferences: ^2.3.2
  permission_handler: ^11.4.0
  geolocator: ^13.0.4
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  http: ^1.2.2
  fl_chart: ^0.69.0
  camera: ^0.11.0+2
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.5
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
